name: frontend_build_check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test echo 1
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          :> ~/.ssh/known_hosts
          chmod 700 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@prolis.tech 'echo hoge >> /tmp/hoge.txt'
