name: frontend_build_check

on:
  push:
    branches:
      - feature/cicd
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production environments
    steps:
      - name: test echo 1
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: prolis.tech
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cat fuga > /tmp/fuga
