name: frontend_build_check

on:
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build the docker image
        shell: bash
        run: cp .env.template .env && docker-compose up -d prod_front
